USE [master]
GO
/****** Object:  Database [TREINAMENTO]    Script Date: 22/08/2025 10:22:10 ******/
CREATE DATABASE [TREINAMENTO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TREINAMENTO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TREINAMENTO.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TREINAMENTO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TREINAMENTO_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TREINAMENTO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TREINAMENTO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TREINAMENTO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TREINAMENTO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TREINAMENTO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TREINAMENTO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TREINAMENTO] SET ARITHABORT OFF 
GO
ALTER DATABASE [TREINAMENTO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TREINAMENTO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TREINAMENTO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TREINAMENTO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TREINAMENTO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TREINAMENTO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TREINAMENTO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TREINAMENTO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TREINAMENTO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TREINAMENTO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TREINAMENTO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TREINAMENTO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TREINAMENTO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TREINAMENTO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TREINAMENTO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TREINAMENTO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TREINAMENTO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TREINAMENTO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TREINAMENTO] SET  MULTI_USER 
GO
ALTER DATABASE [TREINAMENTO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TREINAMENTO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TREINAMENTO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TREINAMENTO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TREINAMENTO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TREINAMENTO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TREINAMENTO] SET QUERY_STORE = OFF
GO
USE [TREINAMENTO]
GO
/****** Object:  UserDefinedFunction [dbo].[FUN_TOTAL_ITEM]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<EDUARDO LEMES>
-- Create date: <11/06/2025>
-- Description:	<FUNÇÃO DE TOTAL DO ITEM>
-- =============================================
CREATE FUNCTION [dbo].[FUN_TOTAL_ITEM] 
(
	@ID INT
)
RETURNS NUMERIC(18,2)
AS
BEGIN
	-- Declare the return variable here
	DECLARE @VR NUMERIC(18,2)

	-- Add the T-SQL statements to compute the return value here
	SELECT @VR = ROUND((ISNULL(VI.QTDE, 0) * ISNULL(VI.VRUNITARIO, 0)),2) FROM VENDAITENS AS VI WHERE VI.ID = @ID

	-- Return the result of the function
	RETURN ROUND(@VR, 2)

END
GO
/****** Object:  UserDefinedFunction [dbo].[FUN_TOTAL_VENDA]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FUN_TOTAL_VENDA] 
(
	@ID INT
)
RETURNS NUMERIC(18,2)
AS
BEGIN
	-- Declare the return variable here
	DECLARE @VR NUMERIC(18,2)

	-- Add the T-SQL statements to compute the return value here
	SELECT @VR = (SELECT ROUND(SUM(ISNULL(TOTALITEM, 0)),2) FROM VENDAITENS AS VI WHERE VI.VENDAID = V.ID) FROM VENDA AS V WHERE V.ID = @ID

	-- Return the result of the function
	RETURN ROUND(@VR, 2)

END
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cpf] [varchar](14) NULL,
	[Nome] [varchar](200) NULL,
	[DataCadastro] [datetime] NULL,
	[Inativo] [bit] NULL,
	[Endereço] [varchar](200) NULL,
	[Numero] [varchar](15) NULL,
	[Complemento] [varchar](100) NULL,
	[Bairro] [varchar](100) NULL,
	[Cidade] [varchar](100) NULL,
	[Estado] [char](2) NULL,
	[Rg] [varchar](15) NULL,
	[Usuario] [varchar](50) NULL,
	[DataGravacao] [datetime] NULL,
	[CNPJ/CPF] [varchar](18) NULL,
	[INSCRICAOESTADUAL] [varchar](30) NULL,
	[CEP] [int] NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ClienteContatos]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ClienteContatos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClienteId] [int] NULL,
	[TipoContato] [varchar](30) NULL,
	[DadosContato] [varchar](300) NULL,
	[Obs] [ntext] NULL,
 CONSTRAINT [PK_ClienteContatos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FormaPagamento]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FormaPagamento](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](100) NULL,
	[Desconto] [numeric](18, 2) NULL,
	[Juros] [numeric](18, 2) NULL,
	[Boleto] [bit] NULL,
 CONSTRAINT [PK_FormaPagamento] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FormaPrazos]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FormaPrazos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FormaId] [int] NULL,
	[Parcela] [int] NULL,
	[Prazo] [int] NULL,
	[Valor] [numeric](18, 2) NULL,
	[Vencimento] [datetime] NULL,
	[FormaDesc] [varchar](50) NULL,
 CONSTRAINT [PK_FormaPrazos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LançamentoBancario]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LançamentoBancario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TituloId] [int] NULL,
	[TipoPagamento] [varchar](50) NULL,
	[DataLancto] [datetime] NULL,
	[PreDate] [datetime] NULL,
	[Conta] [varchar](50) NULL,
	[NrDoc] [varchar](50) NULL,
	[Obs] [varchar](50) NULL,
	[Valor] [numeric](18, 2) NULL,
 CONSTRAINT [PK_LançamentoBancario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Produto]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Produto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [int] NULL,
	[Descricao] [varchar](200) NULL,
	[Data] [datetime] NULL,
	[Movimentacao] [bit] NULL,
	[Grupo] [varchar](30) NULL,
	[Tipo] [varchar](30) NULL,
	[Custo] [numeric](18, 2) NULL,
	[Margem] [numeric](18, 2) NULL,
	[Preco] [numeric](18, 2) NULL,
	[Status] [bit] NULL,
 CONSTRAINT [PK_Produto] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Titulo]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Titulo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DataVencimento] [datetime] NULL,
	[Valor] [numeric](18, 2) NULL,
	[CentroResultado] [varchar](100) NULL,
	[Documento] [varchar](50) NULL,
	[ClienteId] [int] NULL,
	[FormaId] [int] NULL,
	[Tipo] [varchar](30) NULL,
	[VendaId] [int] NULL,
	[QtdParc] [int] NULL,
	[ProxParc] [int] NULL,
	[DataEmissao] [datetime] NULL,
	[Vencido] [int] NULL,
	[ValorBaixado] [numeric](18, 2) NULL,
	[Status] [varchar](50) NULL,
	[IsSelected] [bit] NULL,
 CONSTRAINT [PK_Titulo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Venda]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Venda](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClienteId] [int] NULL,
	[FormaId] [int] NULL,
	[DataPedido] [datetime] NULL,
	[TipoVenda] [varchar](15) NULL,
	[Vendedor] [varchar](50) NULL,
	[Obs] [ntext] NULL,
	[TotalVenda]  AS ([dbo].[FUN_TOTAL_VENDA]([Id])),
	[TotVenda] [numeric](18, 2) NULL,
 CONSTRAINT [PK_Venda] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VendaItens]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VendaItens](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VendaId] [int] NULL,
	[ProdutoId] [int] NULL,
	[Qtde] [numeric](18, 4) NULL,
	[VrUnitario] [numeric](18, 2) NULL,
	[TotalItem]  AS ([dbo].[FUN_TOTAL_ITEM]([Id])),
	[TotItem] [numeric](18, 2) NULL,
	[DescProd] [varchar](50) NULL,
	[NomeCliente] [varchar](50) NULL,
 CONSTRAINT [PK_VendaItens] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ClienteContatos]  WITH CHECK ADD  CONSTRAINT [FK_ClienteContatos_Cliente] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[ClienteContatos] CHECK CONSTRAINT [FK_ClienteContatos_Cliente]
GO
ALTER TABLE [dbo].[FormaPrazos]  WITH CHECK ADD  CONSTRAINT [FK_FormaPrazos_FormaPagamento] FOREIGN KEY([FormaId])
REFERENCES [dbo].[FormaPagamento] ([Id])
GO
ALTER TABLE [dbo].[FormaPrazos] CHECK CONSTRAINT [FK_FormaPrazos_FormaPagamento]
GO
ALTER TABLE [dbo].[LançamentoBancario]  WITH CHECK ADD  CONSTRAINT [FK_LançamentoBancario_Titulo] FOREIGN KEY([TituloId])
REFERENCES [dbo].[Titulo] ([Id])
GO
ALTER TABLE [dbo].[LançamentoBancario] CHECK CONSTRAINT [FK_LançamentoBancario_Titulo]
GO
ALTER TABLE [dbo].[Titulo]  WITH CHECK ADD  CONSTRAINT [FK_Titulo_Cliente] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[Titulo] CHECK CONSTRAINT [FK_Titulo_Cliente]
GO
ALTER TABLE [dbo].[Titulo]  WITH CHECK ADD  CONSTRAINT [FK_Titulo_FormaPagamento] FOREIGN KEY([FormaId])
REFERENCES [dbo].[FormaPagamento] ([Id])
GO
ALTER TABLE [dbo].[Titulo] CHECK CONSTRAINT [FK_Titulo_FormaPagamento]
GO
ALTER TABLE [dbo].[Titulo]  WITH CHECK ADD  CONSTRAINT [FK_Titulo_Venda] FOREIGN KEY([VendaId])
REFERENCES [dbo].[Venda] ([Id])
GO
ALTER TABLE [dbo].[Titulo] CHECK CONSTRAINT [FK_Titulo_Venda]
GO
ALTER TABLE [dbo].[Venda]  WITH CHECK ADD  CONSTRAINT [FK_Venda_Cliente] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[Venda] CHECK CONSTRAINT [FK_Venda_Cliente]
GO
ALTER TABLE [dbo].[Venda]  WITH CHECK ADD  CONSTRAINT [FK_Venda_FormaPagamento] FOREIGN KEY([FormaId])
REFERENCES [dbo].[FormaPagamento] ([Id])
GO
ALTER TABLE [dbo].[Venda] CHECK CONSTRAINT [FK_Venda_FormaPagamento]
GO
ALTER TABLE [dbo].[VendaItens]  WITH CHECK ADD  CONSTRAINT [FK_VendaItens_Produto] FOREIGN KEY([ProdutoId])
REFERENCES [dbo].[Produto] ([Id])
GO
ALTER TABLE [dbo].[VendaItens] CHECK CONSTRAINT [FK_VendaItens_Produto]
GO
ALTER TABLE [dbo].[VendaItens]  WITH CHECK ADD  CONSTRAINT [FK_VendaItens_Venda] FOREIGN KEY([VendaId])
REFERENCES [dbo].[Venda] ([Id])
GO
ALTER TABLE [dbo].[VendaItens] CHECK CONSTRAINT [FK_VendaItens_Venda]
GO
/****** Object:  StoredProcedure [dbo].[PRO_CLIENTE_VENDA]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PRO_CLIENTE_VENDA]
	-- Add the parameters for the stored procedure here
	@DTINICIAL DATETIME,
	@DTFINAL DATETIME
AS
BEGIN
	SELECT     V.ID AS 'VENDA',
			   C.[CNPJ/CPF],
			   C.NOME AS 'CLIENTE',
			   (CASE WHEN ISNULL(C.ENDEREÇO, 'NAO INFORMADO') = '' THEN '' ELSE ISNULL(C.ENDEREÇO, '') + ', ' + ISNULL(C.NUMERO, '') + '-' + ISNULL(C.BAIRRO, '') + ', ' + ISNULL(C.ESTADO, '') END) AS ENDCLIENTE,
			   V.DATAPEDIDO AS 'DATAVENDA',
			   ROUND((SELECT SUM(ISNULL(QTDE, 0) * VRUNITARIO) FROM VENDAITENS AS VI WHERE VI.VENDAID = V.ID),2) AS TOTALVENDA
		  FROM VENDA AS V INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
	INNER JOIN VENDAITENS AS VI ON V.ID = VI.VENDAID
	INNER JOIN PRODUTO AS P ON VI.PRODUTOID = P.ID
		 WHERE V.DATAPEDIDO >= @DTINICIAL
		   AND V.DATAPEDIDO <= @DTFINAL

END
GO
/****** Object:  StoredProcedure [dbo].[PRO_DADOS_VENDAS]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PRO_DADOS_VENDAS] 
	-- Add the parameters for the stored procedure here
	@DTINICIAL DATETIME,
	@DTFINAL DATETIME
AS
BEGIN
	SELECT     V.ID,
			   V.DATAPEDIDO,
			   C.NOME,
			   SUM(VI.QTDE * VI.VRUNITARIO) AS TOTALVENDA,
			   COUNT(VI.ID) AS TOTALITENS,
			   ISNULL(SUM(T.VALOR),0) AS FINANCEIRO
		  FROM VENDA AS V INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
	INNER JOIN VENDAITENS AS VI ON V.ID = VI.VENDAID
	 LEFT JOIN TITULO AS T ON V.ID = T.VENDAID
		 WHERE V.DATAPEDIDO >= @DTINICIAL
		   AND V.DATAPEDIDO <= @DTFINAL
	  GROUP BY V.ID, V.DATAPEDIDO, C.NOME
END
GO
/****** Object:  StoredProcedure [dbo].[PRO_VENDAS_AULA69]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PRO_VENDAS_AULA69] 
	-- Add the parameters for the stored procedure here
	@DTINICIAL DATETIME,
	@DTFINAL DATETIME
AS
BEGIN
	SELECT     V.ID,
			   C.NOME,
			   P.CODIGO AS 'COD-PROD',
			   P.DESCRICAO AS 'PRODUTO',
			   VI.QTDE,
			   VI.VRUNITARIO,
			   ROUND((SELECT SUM(ISNULL(QTDE, 0) * VRUNITARIO) FROM VENDAITENS AS VI WHERE VI.VENDAID = V.ID),2) AS TOTALVENDA
		  FROM VENDA AS V INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
	INNER JOIN VENDAITENS AS VI ON V.ID = VI.VENDAID
	INNER JOIN PRODUTO AS P ON VI.PRODUTOID = P.ID
	 LEFT JOIN TITULO AS T ON V.ID = T.VENDAID
		 WHERE V.DATAPEDIDO >= @DTINICIAL
		   AND V.DATAPEDIDO <= @DTFINAL

END
GO
/****** Object:  StoredProcedure [dbo].[REL_CLIENTES]    Script Date: 22/08/2025 10:22:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<EDUARDO LUCAS LEMES JANUARIO>
-- Create date: <07/08/25>
-- Description:	<Procedure de relatorio para clientes ativos>
-- =============================================
CREATE PROCEDURE [dbo].[REL_CLIENTES] 
	@INATIVO BIT

AS
BEGIN
	SELECT NOME,
		   ISNULL(ENDEREÇO, 'INEXISTENTE') + ' ' + ISNULL(NUMERO, '') + '  ' + ISNULL(COMPLEMENTO, '') AS ENDERECO,
		   (SELECT TOP 1 DADOSCONTATO FROM CLIENTECONTATOS AS CT WHERE C.ID = CT.CLIENTEID AND TIPOCONTATO LIKE '%FONE%') AS CONTATO,
		   CIDADE
	  FROM CLIENTE AS C
	  WHERE C.INATIVO = ISNULL(@INATIVO, C.INATIVO)
END
GO
USE [master]
GO
ALTER DATABASE [TREINAMENTO] SET  READ_WRITE 
GO
