USE TREINAMENTO 
GO

--AULA 64

--SELECTs TESTES
SELECT * FROM FORMAPAGAMENTO

SELECT * FROM FORMAPRAZOS

SELECT * FROM SOLUTEC.DBO.FORMAPAGAMENTO AS FORMASOL

--DELETE
DELETE FROM FORMAPAGAMENTO WHERE DESCRICAO = 'CARTEIRA 30 DIAS'

DELETE FROM FORMAPAGAMENTO

DELETE FROM FORMAPAGAMENTO WHERE ID = 9

--INSERT
INSERT INTO FORMAPAGAMENTO (DESCRICAO, DESCONTO, JUROS, BOLETO)
VALUES ('DINHEIRO', 0,0,0)

INSERT INTO FORMAPAGAMENTO (DESCRICAO, DESCONTO, JUROS, BOLETO)
VALUES ('CREDITO 1X', 2.25,0,0)

INSERT INTO FORMAPAGAMENTO (DESCRICAO, DESCONTO, JUROS, BOLETO)
VALUES ('BOLETO A VISTA', 0,0,1)

INSERT INTO FORMAPRAZOS (FORMAID, PARCELA, PRAZO)
SELECT ID, 
1 AS PARCELA, 
0 AS PRAZO 
FROM FORMAPAGAMENTO

--INSERT EM TABELAS INTERLIGADAS

INSERT INTO FORMAPAGAMENTO(DESCRICAO, DESCONTO, JUROS, BOLETO)
SELECT FORMASOL.DESCRICAO,
FORMASOL.DESCONTO,
FORMASOL.JUROS,
0 AS BOLETO
FROM SOLUTEC.DBO.FORMAPAGAMENTO AS FORMASOL


--DELETES
DELETE FROM FORMAPAGAMENTO

USE TREINAMENTO

--EXERCICIOS
--RESTAURAR O BANCO SOLUTEC

--PEGAR OS DADOS DA SOLUTEC E COLOCAR NA NOSSA
--PRODUTO (USUARIO <> CONVERSÃO AND EMPRESAID = 4 AND INATIVO = 0) E CLIENTES (TUDO -- ALL)

INSERT INTO CLIENTE([CNPJ/CPF], NOME, DATACADASTRO, INATIVO, ENDEREÇO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, INSCRICAOESTADUAL, USUARIO, DATAGRAVACAO)
SELECT FORMASOL.CNPJCPF,
FORMASOL.NOME,
FORMASOL.DATA,
FORMASOL.ENVIASKU,
FORMASOL.ENDERECO,
FORMASOL.NUMERO,
FORMASOL.COMPLEMENTO,
FORMASOL.BAIRRO,
FORMASOL.CIDADE,
FORMASOL.ESTADO,
FORMASOL.INSCRICAOESTADUAL,
FORMASOL.USUARIO,
FORMASOL.DATAINCLUSAO
FROM SOLUTEC.DBO.PESSOA AS FORMASOL

SELECT * FROM CLIENTE

INSERT INTO PRODUTO(CODIGO, DESCRICAO, DATA, MOVIMENTACAO, GRUPO, TIPO, CUSTO, MARGEM, PRECO, STATUS)
SELECT FORMASOL.CODIGO,
FORMASOL.DESCRICAO,
FORMASOL.DATAINCLUSAO,
FORMASOL.ESTOQUE,
FORMASOL.GRUPO,
FORMASOL.TIPO,
FORMASOL.CUSTO,
FORMASOL.MARGEM,
FORMASOL.PRECO,
FORMASOL.INSUMOLOJA
FROM SOLUTEC.DBO.PRODUTO AS FORMASOL

SELECT * FROM PRODUTO 

DELETE FROM PRODUTO WHERE ID > 10



