--AULA 67 - GROUP BY

USE TREINAMENTO

--MODIFICANDO O EXEMPLO ANTERIOR PARA TRAZER O TOTAL
--MOSTRANDO A FUNÇAO GROUP BY

SELECT     V.ID AS 'VENDA',
		   C.NOME AS 'CLIENTE',
	       FP.DESCRICAO AS 'FORMA PAGAMENTO',
		   V.DATAPEDIDO,
		   SUM(VI.QTDE * VI.VRUNITARIO) AS TOTAL,
	       COUNT(V.ID) AS ITENS
	  FROM VENDA AS V INNER JOIN VENDAITENS AS VI ON VI.VENDAID = V.ID
INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
LEFT JOIN  FORMAPAGAMENTO AS FP ON V.FORMAID = FP.ID
INNER JOIN PRODUTO AS P ON VI.PRODUTOID = P.ID
LEFT JOIN  TITULO AS T ON T.VENDAID = V.ID
  GROUP BY V.ID, C.NOME, FP.DESCRICAO, V.DATAPEDIDO
  ORDER BY C.NOME

 --SEMPRE QUE USAR UM SUM, COUNT NUMA CONSULTA
 --USAR O GROUP BY
 --PORQUE QND USAMOS FUNÇÕES DO TIPO QUEREMOS AGRUPAR ALGUM DADO
 --E SEM GROUP BY DARA ERRO
 --O GROUP BY DEVE CONTER TODOS OS ATRIBUTOS, CAMPOS QUE FORAM LISTADOS NO INNER JOIN

 --COUNT CONTA QUANTOS ITENS A EM CADA ID DE VENDA

 --EXERCICIO AULA67

USE TREINAMENTO
GO

--TRAZER DE CLIENTES, NOME, ENDEREÇO, TOTAL DE CONTATOS (COUNT)

SELECT   C.NOME,
		 C.ENDEREÇO,
		 COUNT(CC.ID) AS 'QTD CONTATOS'
	FROM CLIENTE AS C INNER JOIN CLIENTECONTATOS AS CC ON CC.CLIENTEID = C.ID
GROUP BY C.NOME, C.ENDEREÇO
ORDER BY C.NOME

--FORMAS DE PAGAMENTO, * TOTAL DE PRAZOS QUE CADA FORMA DE PAGAMENTO TEM

SELECT   FP.ID,
	     FP.DESCRICAO,
		 FP.DESCONTO,
		 FP.JUROS,
		 FP.BOLETO,
		 COUNT(FPR.ID) AS 'QTD PRAZOS'
	FROM FORMAPAGAMENTO AS FP INNER JOIN FORMAPRAZOS AS FPR ON FPR.FORMAID = FP.ID
GROUP BY FP.ID, FP.DESCRICAO, FP.DESCONTO, FP.JUROS, FP.BOLETO
ORDER BY FP.ID

--SOMATORIA DE TODOS OS ITENS DA TABELA DE VENDAS
--DESC, COD, QTDE E VRUNIT
--TOT DE CADA ITEM 
--CUSTO TOTAL DE CADA ITEM (CUSTO * QTDE)

SELECT     V.DATAPEDIDO,
		   V.ID AS 'VENDA',
		   P.CODIGO AS 'COD PROD',
		   P.DESCRICAO AS 'PRODUTO',
		   VI.QTDE,
		   VI.VRUNITARIO,
		   SUM(VI.QTDE * VI.VRUNITARIO) AS 'TOTAL',
		   SUM(VI.QTDE * P.CUSTO) AS 'CUSTO TOTAL'
      FROM VENDA AS V INNER JOIN VENDAITENS AS VI ON VI.VENDAID = V.ID
INNER JOIN PRODUTO AS P ON VI.PRODUTOID = P.ID
GROUP BY V.DATAPEDIDO, V.ID, P.CODIGO, P.DESCRICAO, VI.QTDE, VI.VRUNITARIO
ORDER BY V.ID, P.DESCRICAO