USE TREINAMENTO

--AULA 66

SELECT     C.NOME,
           P.DESCRICAO,
	       VI.QTDE,
	       VI.VRUNITARIO	   
	  FROM VENDAITENS AS VI INNER JOIN PRODUTO AS P ON VI.PRODUTOID = P.ID
INNER JOIN VENDA AS V ON VI.VENDAID = V.ID
INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
	 WHERE VI.QTDE = 1
  ORDER BY P.DESCRICAO
	
	--SEMPRE UTILIZAR O WHERE POR ULTIMO
	--INNER JOIN PODE SER FEITO QUANTAS VEZES NECESSARIO, MAS
	--SEMPRE LEMBRAR DE REFERENCIAR AS TABELAS CERTAS

SELECT     V.ID,
	       V.DATAPEDIDO,
	       C.NOME,
	       T.DATAVENCIMENTO,
		   FP.DESCRICAO
	  FROM VENDA AS V INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
LEFT JOIN TITULO AS T ON V.ID = T.VENDAID
LEFT JOIN FORMAPAGAMENTO AS FP ON T.FORMAID = FP.ID
WHERE FP.DESCRICAO = 'DEBITO'

--left join prioriza o conjunto de codigo a esquerda

--EXERCICIOS

USE TREINAMENTO

--TRAZER NUMERO DA VENDA, DATAVENDA, NOME DO CLIENTE, DATA DE VENCIMENTO DO TITULO, 
--COD E DESC DO PRODUTO QUE TA NA VENDA, QTDE E VALORUNI, FORMA DE PAGAMENTO
--SEM WHERE

SELECT     V.ID AS 'VENDA',
		   C.NOME AS 'CLIENTE',
		   P.CODIGO AS 'COD PROD',
		   P.DESCRICAO AS 'PRODUTO',
	       FP.DESCRICAO AS 'FORMA PAGAMENTO',
		   VI.QTDE,
		   VI.VRUNITARIO,
	       V.DATAPEDIDO,
	       T.DATAVENCIMENTO
	  FROM VENDA AS V INNER JOIN VENDAITENS AS VI ON VI.VENDAID = V.ID
INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
INNER JOIN FORMAPAGAMENTO AS FP ON V.FORMAID = FP.ID
INNER JOIN PRODUTO AS P ON VI.PRODUTOID = P.ID
LEFT JOIN TITULO AS T ON T.VENDAID = V.ID
  ORDER BY C.NOME

--MODIFICADO PARA TRAZER O TOTAL

SELECT     V.ID AS 'VENDA',
		   C.NOME AS 'CLIENTE',
	       FP.DESCRICAO AS 'FORMA PAGAMENTO',
		   SUM(VI.QTDE * VI.VRUNITARIO) AS TOTAL,
	       V.DATAPEDIDO
	  FROM VENDA AS V INNER JOIN VENDAITENS AS VI ON VI.VENDAID = V.ID
INNER JOIN CLIENTE AS C ON V.CLIENTEID = C.ID
INNER JOIN FORMAPAGAMENTO AS FP ON V.FORMAID = FP.ID
INNER JOIN PRODUTO AS P ON VI.PRODUTOID = P.ID
LEFT JOIN  TITULO AS T ON T.VENDAID = V.ID
  GROUP BY V.ID, C.NOME, FP.DESCRICAO, V.DATAPEDIDO
  ORDER BY C.NOME

 --SEMPRE QUE USAR UM SUM, COUNT NUMA CONSULTA
 --USAR O GROUP BY
 --PORQUE QND USAMOS FUNÇÕES DO TIPO QUEREMOS AGRUPAR ALGUM DADO
 --E SEM GROUP BY DARA ERRO
 --O GROUP BY DEVE CONTER TODOS OS ATRIBUTOS, CAMPOS QUE FORAM LISTADOS NO INNER JOIN


