USE [TREINAMENTO]
GO
/****** Object:  Trigger [dbo].[TG_STATUS_TITULO_INSERT]    Script Date: 18/07/2025 14:28:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<EDUARDO LEMES>
-- Create date: <17/07/25>
-- Description:	<TRIGGER PARA MUDAR STATUS DO TITULO>
-- =============================================
CREATE TRIGGER [dbo].[TG_STATUS_TITULO_BAIXA]
   ON  [dbo].[LançamentoBancario]
   AFTER INSERT
AS 
BEGIN
	DECLARE
	@VALOR DECIMAL(18,2),
	@IDB   INT

	SELECT @IDB = ISNULL(TITULOID, 0) FROM INSERTED

	SELECT @VALOR = ROUND(ISNULL(SUM(VALOR),0),2)
	FROM LANÇAMENTOBANCARIO AS LB
	WHERE LB.TITULOID = @IDB

	UPDATE TITULO SET TITULO.STATUS = (CASE WHEN ROUND(TITULO.VALOR ,2) <= @VALOR THEN
	'LIQUIDADO'
	ELSE
	'ABERTO'
	END) WHERE TITULO.ID = @IDB

	UPDATE TITULO SET TITULO.IsSelected = 'false' WHERE TITULO.ID = @IDB

	UPDATE TITULO SET TITULO.ValorBaixado = 0 WHERE TITULO.ID = @IDB
END
